CREATE TABLE domain_data (domain TEXT PRIMARY KEY, scrub INT DEFAULT 0,
           block INT DEFAULT 0, nothing INT DEFAULT 0);

INSERT INTO domain_data (domain, scrub, block, nothing) VALUES
('www.google.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.facebook.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.youtube.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.baidu.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.yahoo.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.amazon.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.wikipedia.org', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.twitter.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('linkedin.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('weibo.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.bing.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.instagram.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.apple.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.blogspot.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.ask.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.ebay.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.pinterest.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.wordpress.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.paypal.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.tumblr.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.imgur.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.microsoft.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.reddit.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.netflix.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.stackoverflow.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.craigslist.org', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.dropbox.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.github.com', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM())),
('www.stonybrook.edu', ABS(RANDOM()),  ABS(RANDOM()), ABS(RANDOM()));
