/*  exported BLOCKED_STRINGS, ALLOW, DENY, SCRUB, USER_DENY, USER_ALLOW, SWWL,
    CUSTOM_SETTINGS, ACTION_ALLOW, ACTION_DENY, ACTION_SCRUB, ACTION_UNKNOWN*/
/* jshint unused: false */

const BLOCKED_STRINGS = 'BLOCKED_STRINGS';
const ALLOW = 'ALLOW';
const DENY = 'DENY';
const SCRUB = 'SCRUB';
const SWWL = 'SITE_WIDE_WHITE_LIST';
const CUSTOM_SETTINGS = 'CUST_SETTINGS';

const ACTION_ALLOW = 'allow';
const ACTION_DENY = 'deny';
const ACTION_SCRUB = 'scrub';
const ACTION_UNKNOWN = 'unknown';
